export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_COUNT = 'CHANGE_COUNT';
export const CHANGE_ACTIVE_ATTRIBUTES = 'CHANGE_ACTIVE_ATTRIBUTES';
